### ISSUE TITLE
Decentralized Reserve Abacus Prototype

### ISSUE THREAD

**Issue by tobikuhlmann** [mento-protocol/abacus-prototype#2]
This epic describes the work and steps for developing the Decentralized Reserve Abacus Prototype.

### Definition of done
- A set of smart contracts deployed on Alfajores and Kovan which
   - Hold their respective native assets
   - Communicate it's state with each other, calculating the total cross-chain reserve value
   - Are able to send funds to each other to simulate rebalancing. If no tokens available to do so, simulate with messaging
   - Celo / Alfajores contracts own the contracts on Kovan and are the only owners and controllers. 
   - Transactions on Kovan can be invoked from Alfajores, and only be invoked from the respective Alfajores reserve contracts

##### MentoPrototypeGovernance

AbacusController application on Alfajores (local controller) & Kovan (remote)

##### MentoPrototypeToken

AbcERC20 token deployed on Alfajores & Kovan, used for value transfer

##### MentoPrototypeReserve

Router pattern, holds MentoTestToken and a method to send this token between Alfajores and Kovan. Transactions can only be triggered by the Alfajors MentoTestGovernance controller contract

**Comment by nvtaveras** [comment]
This was part of the demo that Tobi built
