### ISSUE TITLE
Ask & get Abacus folks to deploy on Goerli

### ISSUE THREAD

**Issue by tobikuhlmann** [mento-protocol/abacus-prototype#28]
Abacus is deployed on the Ethereum Kovan testnet, The Portal Token Bridge only on Goerli or Ropsten. Ropsten is deprecated, so to test USDC cross-chain rebalancing I need Abacus on Goerli

**Comment by tobikuhlmann** [comment]
they said it's gonna happen but can't promise when

**Comment by nvtaveras** [comment]
Done 🙌
